# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apidatabase:
    image: apidatabase
    build:
      context: .
      dockerfile: apidatabase/Dockerfile
    ports:
      - 5030:5030
